### ISSUE TITLE
Issues deploying Amplify CREATE_FAILED

### ISSUE THREAD

**Issue by joao-d-oliveira** [aws-samples/serverless-pdf-chat#11]
Issues deploying the app in amplify.
Getting errors when deploying sam with "`sam deploy --guided`".
I believe the issue lies on the AWS Secrets... but not sure. If that's the case, perhaps we could specify better the instructions.

### Errors

```
CREATE_FAILED                            AWS::Amplify::App                        AmplifyApp                               Resource handler returned message:     
                                                                                                                           "Invalid request provided: Repository  
                                                                                                                           provider not supported. (Service:      
                                                                                                                           Amplify, Status Code: 400, Request ID: 
                                                                                                                           xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx)" 
                                                                                                                           (RequestToken:                         
                                                                                                                           xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx,  
                                                                                                                           HandlerErrorCode: InvalidRequest)      
UPDATE_ROLLBACK_IN_PROGRESS              AWS::CloudFormation::Stack               serverless-bedrock-goatai-chat           The following resource(s) failed to    
                                                                                                                           create: [AmplifyApp]. 

```

### Steps created

1. Linked Amplify with my [repository](https://github.com/aws-samples/serverless-pdf-chat)
2. Deployed in amplify the repository
3. Added a secret in:  AWS Secrets Manager >  Secrets  > Store a new secret
    - Choose Other type of secret
    - Tried different things:
           - Key/Value (`github_pat_T2wyo:rs0Pp`) (it show in plaintext: `{"github_pat_T2wyo":"rs0Pp"})`
           - Plaintext: '`github_pat_T2wyo------------------------------------------------------------------------rs0Pp`'
4. Try to deploy the backend `sam deploy --guided`

**Comment by pbv0** [comment]
Hi Joao, just to make sure:
- did you create your own GitHub fine-grained access token?
- did you give the secret the exact name mentioned in the readme? `serverless-pdf-chat-github-token`
- did you use this URL in sam deploy --guided? https://github.com/joao-d-oliveira/serverless-pdf-chat

**Comment by joao-d-oliveira** [comment]
hi @pbv0 thanks for replying!

By `did you create your own GitHub fine-grained access token?` if you mean connect Amplify with my GitHub repo and provided access then yes I have done so. If you mean something else, than that might be the missing piece.

All the other steps I have done. It does find the secret (I had initially named something else and got a different error).

**Comment by joao-d-oliveira** [comment]
I realised that I hadn't created a Fine-grained personal access tokens, only connected AWS to GH repo.

So now I tried to:
- created a Fine-grained personal access tokens and got my code: github_pat_11xxxxxxxxxxxxxL3
- I've created in AWS a secret with the name: `serverless-pdf-chat-github-token` and in the "plain_text" tab, I remove the JSON format (`{"":""}`) and just paste normal text: `github_pat_11xxxxxxxxxxxxxL3`
- Then I go and do sam deploy --guided (where I make sure I use the right amplify http and option, ...)

Still I get the same error:

```
CREATE_FAILED                            AWS::Amplify::App                        AmplifyApp                               Resource handler returned message:     
                                                                                                                           "Invalid request provided: Repository  
                                                                                                                           provider not supported. (Service:      
                                                                                                                           Amplify, Status Code: 400, Request ID: 
                                                                                                                           xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx)" 
                                                                                                                           (RequestToken:                         
                                                                                                                           xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxxxxx,  
                                                                                                                           HandlerErrorCode: InvalidRequest)      
UPDATE_ROLLBACK_IN_PROGRESS              AWS::CloudFormation::Stack               serverless-bedrock-goatai-chat           The following resource(s) failed to    
                                                                                                                           create: [AmplifyApp]. 
```

**Comment by pbv0** [comment]
The error message points to Amplify not recognizing the repository provider which should be GitHub. This could be if the URL to the repository is wrong but if you are using https://github.com/joao-d-oliveira/serverless-pdf-chat that would be correct. Are you using https in the URL?

**Comment by joao-d-oliveira** [comment]
@pbv0 thanks for your patience... I realised when you meant on the script "repository" you meant the GitHub link to the repository... I thought that I was supposed to create a amplify app already with the repository and link to the AWS amplify... 

So I was providing the script with the Amplify https... instead of the GH repository, I understood now that the SAM created the app, ... 

Sorry for the trouble and thanks once again!

**Comment by pbv0** [comment]
No worries, thanks for documenting what the issue was.
