### ISSUE TITLE
model parameters

### ISSUE THREAD

**Issue by catalin-hanga** [aws-samples/serverless-pdf-chat#12]
For a particular Bedrock LLM, can we see what are the default values of the model parameters (such as Temperature, Top K, max tokens) that are used by the app, and can we change these values ?

**Comment by pbv0** [comment]
Yes, you can check the default parameters for each Bedrock model here (by default this sample uses Claude v2):
https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html

You can adjust these values by passing `model_kwargs` to the `Langchain` Bedrock class: https://api.python.langchain.com/en/latest/llms/langchain.llms.bedrock.Bedrock.html
