### ISSUE TITLE
Triple equals in requirements.txt

### ISSUE THREAD

**Issue by jeremyallenjacobson** [aws-samples/serverless-pdf-chat#13]
There appears a triple equals

shortuuid===1.0.11

in [backend/src/upload_trigger/requirements.txt](https://github.com/aws-samples/serverless-pdf-chat/blob/main/backend/src/upload_trigger/requirements.txt)

**Comment by pbv0** [comment]
Thanks for pointing this out, corrected in 57e2fd0.
