### ISSUE TITLE
Issue with larger files

### ISSUE THREAD

**Issue by mohsiniqbal368** [aws-samples/serverless-pdf-chat#24]
It works fine until we keep uploading documents of size in KBs or max 1 to 2 MB with 15 to 20 pages.

I tried uploading a 15MB PDF with roughly 400 pages. It gets uploaded on the S3 bucket but embedding extraction doesn't fire and i am unable to see the document on front end as well after upload.

I also tried deploying with increased timeout along with no spaces in the name of that large pdf file but it still doesn't work.

**Comment by pbv0** [comment]
Hi, can you take a look at the Lambda function logs and check what error is coming up? If the document does not show up in the UI, the UploadTrigger function is likely failing.

**Comment by mohsiniqbal368** [comment]
All I can see in Cloudwatch for UploadTrigger is
2023-11-20T17:02:37.976Z d7ee6ba3-62c2-45e6-9aac-2d53b6677503 **Task timed out after 3.23 seconds**

increased the timeout in Lambda configuration tab and its working fine now.

**Comment by dariushazimi** [comment]
@pbv0 
Hi Pascal, Increased the timeout on the lambda func "UploadTrigger function " but a file with about 32MB does not show up on the UI. It is uploaded on the S3 bucket but not listed on UI.
