### ISSUE TITLE
delete documents

### ISSUE THREAD

**Issue by mohsiniqbal368** [aws-samples/serverless-pdf-chat#26]
How can we cleanly delete documents. Is deleting FAISS index from S3 sufficient?

**Comment by pbv0** [comment]
1. Delete the FAISS dump in S3
2. Delete all conversations with the file from the DynamoDB `MemoryTable`
3. Delete the entry of the file from the DynamoDB `DocumentTable`

**Comment by pbv0** [comment]
Closing this for now, please reopen if anything is unclear.
