### ISSUE TITLE
Amazon Kendra in place of Embedding Model

### ISSUE THREAD

**Issue by mohsiniqbal368** [aws-samples/serverless-pdf-chat#28]
Hi,

What could be the possible benefit and drawback of using Amazon Kendra for RAGing instead of using Embedding Model (Titan-1)/FAISS for similarity search. Cost could be one factor I suppose, what about the overall chat performance and answers accuracy in both cases?

**Comment by pbv0** [comment]
Kendra is a fully-managed search service, so it will take care of much of the work you have to do when manually generating embeddings etc.

Regarding performance, I would suggest to try out different approaches for your specific type of documents, it's not possible to make a general assessment here.

We offer several sample for RAG with Kendra, for example here. https://github.com/aws-samples/aws-bedrock-with-rag-and-react
