### ISSUE TITLE
Document uploaded but not getting process

### ISSUE THREAD

**Issue by IshtiyaqKhanAlld** [aws-samples/serverless-pdf-chat#32]
I build and deployed the application 2 times but getting the same issue mentioned below :
1. Document uploaded in s3 but not getting process, I was waiting for 30 minutes for 130 kb doc.
 Err log details :
[ERROR] ValueError: Error raised by inference endpoint: An error occurred (AccessDeniedException) when calling the InvokeModel operation: You don't have access to the model with the specified model ID.
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/logging/logger.py", line 453, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/main.py", line 57, in lambda_handler
    index_from_loader = index_creator.from_loaders([loader])
  File "/var/task/langchain/indexes/vectorstore.py", line 82, in from_loaders
    return self.from_documents(docs)
  File "/var/task/langchain/indexes/vectorstore.py", line 87, in from_documents
    vectorstore = self.vectorstore_cls.from_documents(
  File "/var/task/langchain/schema/vectorstore.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/var/task/langchain/vectorstores/faiss.py", line 911, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/var/task/langchain/embeddings/bedrock.py", line 143, in embed_documents
    response = self._embedding_func(text)
  File "/var/task/langchain/embeddings/bedrock.py", line 130, in _embedding_func
    raise ValueError(f"Error raised by inference endpoint: {e}") 

<img width="950" alt="image" src="https://github.com/aws-samples/serverless-pdf-chat/assets/112078629/7674ec79-edfc-457d-
<img width="950" alt="Issue-AWS-Serverless-Pdf-chat" src="https://github.com/aws-samples/serverless-pdf-chat/assets/112078629/67c4a773-3fa4-4c5e-9800-c96034b36b89">
92ed-38bc87ee42a8">

**Comment by pbv0** [comment]
Hi, please check that you have activated the Anthropic Claude model in the correct AWS Region. Per default this is us-east-1 (independently from where you deploy the SAM stack): https://docs.aws.amazon.com/bedrock/latest/userguide/model-access.html

Let me know if this solves the problem.

**Comment by pushpsood** [comment]
+1 to @pbv0 
While trying to request the access I got INVALID_PAYMENT_INSTRUMENT in Bedrock, for now using Titan(one will get the approval for this model) instead of Llama 2, and will switch once the ticket is resolved and update how it could be fixed.

**Comment by pbv0** [comment]
@pushpsood it looks like some third-party model providers require credit card as payment method and do not support some other options (e.g. direct debit): https://repost.aws/questions/QU0UOsutrWSSS4nOqgHcIUJg/invalid-payment-instrument-after-requesting-model-access-in-amazon-bedrock

**Comment by pbv0** [comment]
Closing this for now, feel free to reopen if the issue remains.
