### ISSUE TITLE
Issue with cognito

### ISSUE THREAD

**Issue by fbanespo1** [aws-samples/serverless-pdf-chat#4]
Good afternoon,

I have an issue with cognito I created the user and when hit http://127.0.0.1:5173/ I get this error
Configuration error (see console) – please contact the administrator

Any idea how to fix that?
Thanks
Tony

**Comment by pbv0** [comment]
Hi @fbanespo1 , can you check the browser console for the error?

This likely has to do with the information you put into the .env.development file (Cognito user pool ID etc.). Please double check if you are using the right information form the CloudFormation output.

**Comment by fbanespo1** [comment]
> Hi @fbanespo1 , can you check the browser console for the error?
> 
> This likely has to do with the information you put into the .env.development file (Cognito user pool ID etc.). Please double check if you are using the right information form the CloudFormation output.

I am sorry -- outlooked the step of .env...nor it works 👍
