### ISSUE TITLE
Breaking change in LangChain/FAISS

### ISSUE THREAD

**Issue by datasith** [aws-samples/serverless-pdf-chat#45]
For folks running into:

```python 
 ValueError: The de-serialization relies loading a pickle file. Pickle files can
 be modified to deliver a malicious payload that results in execution of
 arbitrary code on your machine.You will need to set
 `allow_dangerous_deserialization` to `True` to enable deserialization. If you do
 this, make sure that you trust the source of the data. For example, if you are
 loading a file that you created, and no that no one else has modified the file,
 then this is safe to do. Do not set this to `True` if you are loading a file
 from an untrusted source (e.g., some random site on the internet.
```

It is due to a recent, intentional [code-breaking change](https://github.com/langchain-ai/langchain/commit/4c25b4922987fce0317f4e75e84d4a7381ad7dcb).

Update [this line](https://github.com/aws-samples/serverless-pdf-chat/blob/cc77aba9ca6c81c4aac1e0ea06dc118abafb3181/backend/src/generate_response/main.py#L44) in the generate response Lambda:
```python
faiss_index = FAISS.load_local("/tmp", embeddings)
```
to:

```python
faiss_index = FAISS.load_local("/tmp", embeddings, allow_dangerous_deserialization=True)
```

and re-deploy in any preferred way. 

Also, please take a moment to consider why this change was made, and the security risks associated with loading [pickle files](https://intoli.com/blog/dangerous-pickles/).

**Comment by moserda** [comment]
Hi, since this has been resolved in c4a8d2b I'll close this issue.
