### ISSUE TITLE
Documents not being processed

### ISSUE THREAD

**Issue by jcnovoa** [aws-samples/serverless-pdf-chat#5]
Getting this error in CloudWatch... I can successfully upload documents, and hae enabled the required default models. I am an admin on the AWS account, so not sure what is broken, see attached screenshots related to the configuration:
/aws/lambda/serverless-pdf-chat-UploadTriggerFunction-PUtyPtTBkmCD

[ERROR] ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/logging/logger.py", line 441, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/main.py", line 31, in lambda_handler
    s3.download_file(BUCKET, key, f"/tmp/{file_name}")
  File "/var/task/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/var/task/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/var/task/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/var/task/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/var/task/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/var/task/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/var/task/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
    
    Can't find the doc which exist in S3
    {
    "level": "INFO",
    "location": "lambda_handler:38",
    "message": {
        "user_id": "a4a834f8-b0a1-70c1-f51c-553c822b6d7a",
        "file_name_full": "Product+User+Guide 2023.pdf",
        "file_name": "Product+User+Guide 2023",
        "exists": false
    },
    "timestamp": "2023-10-06 16:35:38,172+0000",
    "service": "service_undefined",
    "cold_start": true,
    "function_name": "serverless-pdf-chat-GeneratePresignedUrlFunction-2rY1oozX2qBn",
    "function_memory_size": "128",
    "function_arn": "arn:aws:lambda:us-east-1:YYYYZZZZXXXX:function:serverless-pdf-chat-GeneratePresignedUrlFunction-2rY1oozX2qBn",
    "function_request_id": "ad0df0cc-2783-4ea1-ae3f-401b2e9b6f0e",
    "xray_trace_id": "1-65203758-4a9505ab411cd0080d4f035f"
}
![Screenshot 2023-10-06 at 12 38 18 PM](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/3e85cee7-6c7b-4cde-8139-4275eb8608a0)
![Screenshot 2023-10-06 at 12 37 17 PM](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/e546bf69-d966-4fe0-a05e-d71948c29bd8)
![Screenshot 2023-10-06 at 12 36 56 PM](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/a0418aff-0852-407a-9e0a-841453be77e0)
![Screenshot 2023-10-06 at 12 35 52 PM](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/d3831913-8000-44be-a453-4f17f8c351b8)
![Screenshot 2023-10-06 at 12 32 51 PM](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/8d651df2-093b-46c7-9db6-28fbcbba457b)

**Comment by awsperez** [comment]
Just a wild guess....can you rename the PDF to remove the "+" signs?

**Comment by jcnovoa** [comment]
> Just a wild guess....can you rename the PDF to remove the "+" signs?
I also tried that, still no luck... also looks like lots of the Lambdas deployed have the "3 second" exec. limit, so changed that also. Additionally, did check the payload, and seems like when sent to Lambda, it is encapsualted inside the "message" object, yet the Lambdas do not account for that... still debuging :-(

**Comment by pbv0** [comment]
This is most likely due to the PDF file names, try without any spaces or special characters.

I'll look into a fix in the next days to make this a bit more robust.

Let me know the file names where you're having the errors.

**Comment by jcnovoa** [comment]
> This is most likely due to the PDF file names, try without any spaces or special characters.
> 
> I'll look into a fix in the next days to make this a bit more robust.
> 
> Let me know the file names where you're having the errors.

Actually it turned out to be that the documentation and the outputs of the CFT stack direect us to use the "/dev" stage, yet all the Lambdas integrations are with the "/Stage" stage. Once I changed that in the .env.development variables and changed the time limit in the Lambdas, it worked fine... perhaps update the documentation if it is found this was the root cause.
![Trigger](https://github.com/aws-samples/serverless-pdf-chat/assets/1389127/584580ab-8519-4eaf-8f5c-9644464bc4d9)

**Comment by pbv0** [comment]
Hi @jcnovoa , thanks for digging into this.

Regarding the `Stage` stage, this is created automatically by AWS SAM for legacy reasons, [see here for details](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion). The API will still work with the `dev` stage.

Regarding timeouts, there are two Lambda functions which need a longer timeout because they communicate with the LLM, `GenerateEmbeddings` and `GenerateResponse`.

`GenerateEmbeddings` Lambda function has a 300 second timeout which should be more than enough.

`GenerateResponse` has a timeout of 30 seconds. This function is invoked synchronously via the API Gateway which itself has a 29 second max timeout, so a larger timeout on the Lambda function won't do much good for the immediate request.

The other functions with the lower timeout values are only used for CRUD with DynamoDB so they don't need a long timout.

**Comment by pbv0** [comment]
Closing this for now, let me know if there are any open questions.
