### ISSUE TITLE
conversation history

### ISSUE THREAD

**Issue by catalin-hanga** [aws-samples/serverless-pdf-chat#7]
Where are the conversations being stored, and how can we delete the conversation history with a particular document ?

**Comment by awsperez** [comment]
Conversations are being stored in the DynamoDB database. I think you'd need to directly delete the record from the database.  At this point the UI does not have that functionality.

**Comment by pbv0** [comment]
Exactly, we're using LangChain's [`DynamoDBChatMessageHistory`](https://python.langchain.com/docs/integrations/memory/aws_dynamodb#dynamodbchatmessagehistory) and you can find the stored history in the `serverless-pdf-chat-MemoryTable` DynamoDB table.

**Comment by pbv0** [comment]
Closing this for now, please raise a new issue if anything is unclear.
