### ISSUE TITLE
Big document

### ISSUE THREAD

**Issue by fbanespo1** [aws-samples/serverless-pdf-chat#8]
Hi Pascal,

It is working very well, I had other similar solutions but this one looks really nice. I have a question if I can: I ingested a big pdf, not in size but in pages and wasn't create any FAISS index and the document don't appear in the main dashboard. Do you think it's possible to make it available also for big files?

Thanks
Tony

**Comment by pbv0** [comment]
Hi Tony, can you share more information on the file size, number of pages, file name, etc.? There is no built-in blocker for large numbers of pages, I've tested with documents with a couple of hundred of pages.

There were some issues with file names with spaces, that could be one reason.

You can check the logs of the Lambda functions (especially `generateEmbeddings`) to see what exactly is going wrong.

**Comment by fbanespo1** [comment]
> Hi Tony, can you share more information on the file size, number of pages, file name, etc.? There is no built-in blocker for large numbers of pages, I've tested with documents with a couple of hundred of pages.
> 
> There were some issues with file names with spaces, that could be one reason.
> 
> You can check the logs of the Lambda functions (especially `generateEmbeddings`) to see what exactly is going wrong.

Hi Pascal,

The file size is 12MB but contains more than 1000 pages inside. The file name is correct and the lambda log doesn't show any error, but inside the S3 directory I don't see any FAISS index created like in the other folders. It seems the lambda start but goes in timeout probably because the index generation is too big for the lambda timeout. I am just guessing.

Thanks
Tony

**Comment by pbv0** [comment]
Ok, then this might be due to the generateEmbeddings Lambda function timing out. You can increase the function timeout in the backend/template.py. But at some point it might become more efficient to switch to a dedicated vector DB.

**Comment by pbv0** [comment]
Closing this for now, let me know if there are any open questions.
